CARS = [
    {"id_car": "00001", "brand": "Toyota", "model": "Camry", "year":2020, "color":"black", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00002", "brand": "Mercedes-Benz", "model": "GLE", "year":2023, "color":"red", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00003", "brand": "BMW", "model": "320i", "year":2015, "color":"white", "province":"Alberta", "city": "Calgary"},
    {"id_car": "00004", "brand": "Audi", "model": "Q5", "year":2013, "color":"black", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00005", "brand": "Toyota", "model": "Corolla", "year":2022, "color":"blue", "province":"Ontario", "city": "Kingston"},
    {"id_car": "00006", "brand": "Ford", "model": "Edge", "year":2021, "color":"silver", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00007", "brand": "Ford", "model": "Broncos", "year":2017, "color":"black", "province":"Ontario", "city": "Burlington"},
    {"id_car": "00008", "brand": "Audi", "model": "eTron Q4", "year":2018, "color":"white", "province":"Alberta", "city": "Calgary"},
    {"id_car": "00009", "brand": "Toyota", "model": "Rav4", "year":2017, "color":"silver", "province":"Manitoba", "city": "Winnipeg"},
    {"id_car": "00010", "brand": "Ford", "model": "Explorer", "year":2018, "color":"silver", "province":"Ontario", "city": "Oshawa"},
    {"id_car": "00011", "brand": "Wolkswagen", "model": "Tiguan", "year":2023, "color":"blue", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00012", "brand": "Crysler", "model": "Pacifica", "year":2021, "color":"black", "province":"Quebec", "city": "Laval"},
    {"id_car": "00013", "brand": "Toyota", "model": "Rav4", "year":2020, "color":"red", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00014", "brand": "Mitshubishi", "model": "Outlander", "year":2020, "color":"black", "province":"Ontario", "city": "Oakville"},
    {"id_car": "00015", "brand": "Nissan", "model": "Sentra", "year":2017, "color":"silver", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00016", "brand": "Ford", "model": "Mustang", "year":2018, "color":"white", "province":"Alberta", "city": "Calgary"},
    {"id_car": "00017", "brand": "Wolkswagen", "model": "Atlas", "year":2020, "color":"silver", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00018", "brand": "Toyota", "model": "Camry", "year":2023, "color":"white", "province":"Ontario", "city": "Oakville"},
    {"id_car": "00019", "brand": "Acura", "model": "RDX", "year":2021, "color":"white", "province":"Ontario", "city": "Scarborough"},
    {"id_car": "00020", "brand": "Honda", "model": "Civic", "year":2024, "color":"black", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00021", "brand": "Cadillac", "model": "Escalade", "year":2024, "color":"silver", "province":"Manitoba", "city": "Winnipeg"},
    {"id_car": "00022", "brand": "Tesla", "model": "Model 3", "year":2025, "color":"silver", "province":"Alberta", "city": "Calgary"},
    {"id_car": "00023", "brand": "Tesla", "model": "Model Y", "year":2023, "color":"blue", "province":"Ontario", "city": "Oshawa"},
    {"id_car": "00024", "brand": "Toyota", "model": "Rav4", "year":2021, "color":"blue", "province":"Ontario", "city": "Scarborough"},
    {"id_car": "00025", "brand": "Honda", "model": "Pilot", "year":2020, "color":"red", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00026", "brand": "Acura", "model": "MDX", "year":2017, "color":"blue", "province":"Ontario", "city": "Kingston"},
    {"id_car": "00027", "brand": "Toyota", "model": "Corolla", "year":2017, "color":"blue", "province":"Alberta", "city": "Calgary"},
    {"id_car": "00028", "brand": "Toyota", "model": "Highlander", "year":2018, "color":"red", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00029", "brand": "Hyundai", "model": "Pallisade", "year":2023, "color":"blue", "province":"Alberta", "city": "Edmonton"},
    {"id_car": "00030", "brand": "Mercedes-Benz", "model": "S350", "year":2020, "color":"silver", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00031", "brand": "Tesla", "model": "Model S", "year":2021, "color":"black", "province":"Quebec", "city": "Laval"},
    {"id_car": "00032", "brand": "Toyota", "model": "Corolla", "year":2022, "color":"white", "province":"Ontario", "city": "Mississauga"},
    {"id_car": "00033", "brand": "Nissan", "model": "Sentra", "year":2021, "color":"black", "province":"Alberta", "city": "Calgary"},
    {"id_car": "00034", "brand": "Hyundai", "model": "Tucson", "year":2023, "color":"silver", "province":"British Columbia", "city": "Vancouver"},
    {"id_car": "00035", "brand": "Kia", "model": "Telluride", "year":2024, "color":"blue", "province":"Ontario", "city": "Scarborough"},
    {"id_car": "00036", "brand": "Nissan", "model": "Murano", "year":2020, "color":"red", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00037", "brand": "Honda", "model": "Civic", "year":2019, "color":"red", "province":"Manitoba", "city": "Winnipeg"},
    {"id_car": "00038", "brand": "Hyundai", "model": "SantaFe", "year":2023, "color":"red", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00039", "brand": "Hyundai", "model": "iOniq", "year":2024, "color":"blue", "province":"Alberta", "city": "Calgary"},
    {"id_car": "00040", "brand": "Tesla", "model": "Model 3", "year":2021, "color":"blue", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00041", "brand": "Nissan", "model": "Rogue", "year":2022, "color":"black", "province":"Ontario", "city": "Ottawa"},
    {"id_car": "00042", "brand": "Tesla", "model": "Cybertruck", "year":2024, "color":"silver", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00043", "brand": "Dodge", "model": "Durango", "year":2017, "color":"silver", "province":"Ontario", "city": "Kingston"},
    {"id_car": "00044", "brand": "Hyundai", "model": "SantaFe", "year":2019, "color":"silver", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00045", "brand": "Nissan", "model": "Pathfinder", "year":2020, "color":"blue", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00046", "brand": "Honda", "model": "CRV", "year":2021, "color":"red", "province":"Ontario", "city": "Ottawa"},
    {"id_car": "00047", "brand": "Tesla", "model": "Model Y", "year":2022, "color":"red", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00048", "brand": "Dodge", "model": "Challenger", "year":2017, "color":"white", "province":"Ontario", "city": "Mississauga"},
    {"id_car": "00049", "brand": "Cadillac", "model": "Lyriq", "year":2023, "color":"white", "province":"Ontario", "city": "Kingston"},
    {"id_car": "00050", "brand": "Tesla", "model": "Model S Plaid", "year":2015, "color":"silver", "province":"Quebec", "city": "Montreal"},
    {"id_car": "00051", "brand": "Kia", "model": "Sportage", "year":2016, "color":"black", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00052", "brand": "Nissan", "model": "Altima", "year":2015, "color":"blue", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00053", "brand": "Mazda", "model": "cz30", "year":2022, "color":"blue", "province":"Quebec", "city": "Laval"},
    {"id_car": "00054", "brand": "Volvo", "model": "xc90", "year":2021, "color":"red", "province":"Ontario", "city": "Kingston"},
    {"id_car": "00055", "brand": "Kia", "model": "ev9", "year":2025, "color":"red", "province":"Alberta", "city": "Edmonton"},
    {"id_car": "00056", "brand": "Tesla", "model": "Model X", "year":2024, "color":"white", "province":"Ontario", "city": "Ottawa"},
    {"id_car": "00057", "brand": "Hyundai", "model": "Elantra", "year":2017, "color":"white", "province":"Manitoba", "city": "Winnipeg"},
    {"id_car": "00058", "brand": "Hyundai", "model": "Sonata", "year":2025, "color":"black", "province":"Ontario", "city": "Ottawa"},
    {"id_car": "00059", "brand": "Mercedes-Benz", "model": "GLA", "year":2020, "color":"black", "province":"Alberta", "city": "Edmonton"},
    {"id_car": "00060", "brand": "Mercedes-Benz", "model": "E Class", "year":2018, "color":"blue", "province":"Quebec", "city": "Laval"},
    {"id_car": "00061", "brand": "Lexus", "model": "RX 350", "year":2023, "color":"silver", "province":"Ontario", "city": "Ottawa"},
    {"id_car": "00062", "brand": "Infiniti", "model": "QX60", "year":2017, "color":"white", "province":"Ontario", "city": "Toronto"},
    {"id_car": "00063", "brand": "Hyundai", "model": "Tucson", "year":2021, "color":"black", "province":"British Columbia", "city": "Vancouver"}
    
]